services:
  db:
    container_name: postgres-ru-gram-backend
    image: postgres:15.2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ru-gram-backend

  redis:
    container_name: redis-ru-gram-backend
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - ru-gram-backend

volumes:
  postgres_data:
  redis_data:

networks:
  ru-gram-backend:
